# build the example program maximum from chapter 3 
maximum:
	as	maximum.s	-o	./obj/maximum.o
	ld	./obj/maximum.o	-o	./bin/maximum

clean:
	rm	-f	./obj/maximum.o
	rm	-f	./bin/maximum

run:
	-./bin/maximum
